### ISSUE TITLE
deployment failed: 404: NOT_FOUND

### ISSUE THREAD

**Issue by MartinMatomo** [niteshbhaiya4224/StreamingApi#1]
Hello. Thanks for your work, I'm trying to test it but the deployment didn't work: 404: NOT_FOUND
![Screenshot_703](https://github.com/user-attachments/assets/4b436b6c-37c9-4f99-b830-1ed9fa93b4bd)

**Comment by niteshbhaiya4224** [comment]
Hey I am trying to fix this just give me some time will fix it as soon as possible

**Comment by niteshbhaiya4224** [comment]
Deployment FIxed you can check on this url Thanks https://streaming-api-seven.vercel.app/
